### ISSUE TITLE
Possibly need to flush stdout before process.exit()

### ISSUE THREAD

**Issue by michaeljones** [pausan/mocha-list-tests#5]
Thanks for the project. It is providing super useful and it looks like a very elegant solution.

I am seeing an issue when running on a CI set up on MacOS. I'm running the script version of this in a `childProcess.execSync` but it sometimes returns an incomplete JSON structure. It looks like the regular JSON but it is just cut off at some random character.

I think it might be because, on CI, stdout is kind of a pipe? And according to the docs, [writing to a pipe isn't blocking](https://nodejs.org/api/process.html#process_process_stdout) so the `process.exit()` might be called before the JSON structure has finished writing to `stdout`.

I can't see reference to a `process.stdout.flush()` though maybe it exists under a different name. If it did, I would recommend calling it after the final `console.log`. This StackOverflow answer suggests using the callback parameter of `process.stdout.write` which I guess could be wrapped out with a promise and awaited on.

I've added this code to my CI script and it seems to be working more reliably now though maybe that is just luck. I'll try to report back if I see the issue again:

```javascript
/* Patch the npm package that we're using to remove a process.exit which might be triggering before the stdout content
 * has been flushed which results in the output being truncated.
 */
function fixMochaListTests() {
    const filename = path.join('node_modules', 'mocha-list-tests', 'mocha-list-tests.js');
    const content = fs.readFileSync(filename, 'utf-8');
    const filteredContent = content
        .split('\n')
        .filter((line) => line.trim() !== 'process.exit (result);')
        .join('\n');
    fs.writeFileSync(filename, filteredContent);
}
```

**Comment by pausan** [comment]
I've just pushed version 1.0.6 with a fix for this. Thx for reporting it and the context

**Comment by michaeljones** [comment]
Wow, thanks so much for the quick turn around. Much appreciated!

**Comment by pausan** [comment]
You are welcome. I hope the solution works as expected, I could not reproduce the original issue, but I've read some docs and I thought this should make it work.
